# Generated by Django 5.2.2 on 2026-03-25 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('DE', 'German'), ('IT', 'Italian'), ('PT', 'Portuguese'), ('JA', 'Japanese'), ('ZH', 'Chinese')], max_length=2)),
                ('audio_file', models.FileField(upload_to='media/')),
                ('lrc_file', models.FileField(upload_to='media/')),
                ('background_image', models.FileField(upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('JAZZ', 'Jazz'), ('HIPHOP', 'Hip-Hop'), ('CLASSICAL', 'Classical'), ('REGGAE', 'Reggae'), ('LATIN', 'Latin'), ('KPOP', 'K-Pop'), ('COUNTRY', 'Country'), ('BLUES', 'Blues'), ('FOLK', 'Folk'), ('ELECTRONIC', 'Electronic'), ('R&B', 'R&B'), ('SOUL', 'Soul'), ('METAL', 'Metal'), ('PUNK', 'Punk'), ('ALTERNATIVE', 'Alternative'), ('INDIE', 'Indie'), ('GOSPEL', 'Gospel'), ('WORLD', 'World Music')], max_length=20)),
                ('number_times_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SongUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('correct_guesses', models.IntegerField(default=0)),
                ('wrong_guesses', models.IntegerField(default=0)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song_models.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
